pipeline {

  agent any
  environment {
    //adding a comment for the commit test
    ANYPOINT = credentials('deploy-anypoint-user')
    MULE_VERSION = '4.2.2'
    WORKER = "Micro"
  }
  stages {
    stage('Build') {
      steps {
            bat 'mvn -B -U -e -V clean -DskipTests install'
      }
    }

    stage('Test') {
      steps {
          bat "mvn test"
      }
    }

     stage('Deploy Development') {
      environment {
        ENVIRONMENT = 'Sandbox'
        APP_NAME = 'munitcicd'
      }
      steps {
            bat 'mvn -U -V -e -B -DskipTests deploy -DmuleDeploy -Dmule.version="%MULE_VERSION%" -Danypoint.username="%ANYPOINT_USR%" -Danypoint.password="%ANYPOINT_PSW%" -Dcloudhub.app="%APP_NAME%" -Dcloudhub.environment="%ENVIRONMENT%"  -Dcloudhub.worker="%WORKER%"'
      }
    }
  
  }
  tools {
        maven 'maven' 
    }
  

}